package ru.rsdn.janus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "JanusATSoap", targetNamespace = "http://rsdn.ru/Janus/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface JanusATSoap {


    /**
     * \u00c2\u00fb\u00f2\u00ff\u00e3\u00e8\u00e2\u00e0\u00ed\u00e8\u00e5 \u00f2\u00ee\u00ef\u00e8\u00ea\u00ee\u00e2 \u00ef\u00ee ID \u00f1\u00ee\u00ee\u00e1\u00f9\u00e5\u00ed\u00e8\u00e9
     *
     * @param topicRequest
     * @return returns ru.rsdn.janus.TopicResponse
     */
    @WebMethod(operationName = "GetTopicByMessage", action = "http://rsdn.ru/Janus/GetTopicByMessage")
    @WebResult(name = "GetTopicByMessageResult", targetNamespace = "http://rsdn.ru/Janus/")
    @RequestWrapper(localName = "GetTopicByMessage", targetNamespace = "http://rsdn.ru/Janus/", className = "ru.rsdn.janus.GetTopicByMessage")
    @ResponseWrapper(localName = "GetTopicByMessageResponse", targetNamespace = "http://rsdn.ru/Janus/", className = "ru.rsdn.janus.GetTopicByMessageResponse")
    public TopicResponse getTopicByMessage(
            @WebParam(name = "topicRequest", targetNamespace = "http://rsdn.ru/Janus/")
                    TopicRequest topicRequest
    );

    /**
     * \u00c8\u00e7\u00ec\u00e5\u00ed\u00e5\u00ed\u00e8\u00ff \u00e2 \u00f4\u00ee\u00f0\u00f3\u00ec\u00e5 \u00f1 \u00ec\u00ee\u00ec\u00e5\u00ed\u00f2\u00e0 \u00ef\u00ee\u00f1\u00eb\u00e5\u00e4\u00ed\u00e5\u00e9 \u00f1\u00e8\u00ed\u00f5\u00f0\u00ee\u00ed\u00e8\u00e7\u00e0\u00f6\u00e8\u00e8
     *
     * @param changeRequest
     * @return returns ru.rsdn.janus.ChangeResponse
     */
    @WebMethod(operationName = "GetNewData", action = "http://rsdn.ru/Janus/GetNewData")
    @WebResult(name = "GetNewDataResult", targetNamespace = "http://rsdn.ru/Janus/")
    @RequestWrapper(localName = "GetNewData", targetNamespace = "http://rsdn.ru/Janus/", className = "ru.rsdn.janus.GetNewData")
    @ResponseWrapper(localName = "GetNewDataResponse", targetNamespace = "http://rsdn.ru/Janus/", className = "ru.rsdn.janus.GetNewDataResponse")
    public ChangeResponse getNewData(
            @WebParam(name = "changeRequest", targetNamespace = "http://rsdn.ru/Janus/")
                    ChangeRequest changeRequest
    );

    /**
     * \u00d1\u00ef\u00e8\u00f1\u00ee\u00ea \u00f4\u00ee\u00f0\u00f3\u00ec\u00ee\u00e2 \u00e8 \u00e3\u00f0\u00f3\u00ef\u00ef \u00f4\u00ee\u00f0\u00f3\u00ec\u00ee\u00e2
     *
     * @param forumRequest
     * @return returns ru.rsdn.janus.ForumResponse
     */
    @WebMethod(operationName = "GetForumList", action = "http://rsdn.ru/Janus/GetForumList")
    @WebResult(name = "GetForumListResult", targetNamespace = "http://rsdn.ru/Janus/")
    @RequestWrapper(localName = "GetForumList", targetNamespace = "http://rsdn.ru/Janus/", className = "ru.rsdn.janus.GetForumList")
    @ResponseWrapper(localName = "GetForumListResponse", targetNamespace = "http://rsdn.ru/Janus/", className = "ru.rsdn.janus.GetForumListResponse")
    public ForumResponse getForumList(
            @WebParam(name = "forumRequest", targetNamespace = "http://rsdn.ru/Janus/")
                    ForumRequest forumRequest
    );

    /**
     * \u00cf\u00ee\u00eb\u00f3\u00f7\u00e5\u00ed\u00e8\u00e5 \u00ed\u00ee\u00e2\u00fb\u00f5 \u00ef\u00ee\u00eb\u00fc\u00e7\u00ee\u00e2\u00e0\u00f2\u00e5\u00eb\u00e5\u00e9 \u00f1 \u00ec\u00ee\u00ec\u00e5\u00ed\u00f2\u00e0 \u00ef\u00ee\u00f1\u00eb\u00e5\u00e4\u00ed\u00e5\u00e9
     * \u00f1\u00e8\u00ed\u00f5\u00f0\u00ee\u00ed\u00e8\u00e7\u00e0\u00f6\u00e8\u00e8
     *
     * @param userRequest
     * @return returns ru.rsdn.janus.UserResponse
     */
    @WebMethod(operationName = "GetNewUsers", action = "http://rsdn.ru/Janus/GetNewUsers")
    @WebResult(name = "GetNewUsersResult", targetNamespace = "http://rsdn.ru/Janus/")
    @RequestWrapper(localName = "GetNewUsers", targetNamespace = "http://rsdn.ru/Janus/", className = "ru.rsdn.janus.GetNewUsers")
    @ResponseWrapper(localName = "GetNewUsersResponse", targetNamespace = "http://rsdn.ru/Janus/", className = "ru.rsdn.janus.GetNewUsersResponse")
    public UserResponse getNewUsers(
            @WebParam(name = "userRequest", targetNamespace = "http://rsdn.ru/Janus/")
                    UserRequest userRequest
    );

    /**
     * \u00cf\u00ee\u00eb\u00f3\u00f7\u00e5\u00ed\u00e8\u00e5 \u00ef\u00ee\u00eb\u00fc\u00e7\u00ee\u00e2\u00e0\u00f2\u00e5\u00eb\u00e5\u00e9 \u00ef\u00ee \u00f1\u00ef\u00e8\u00f1\u00ea\u00f3 \u00e8\u00f5 \u00e8\u00e4\u00e5\u00ed\u00f2\u00e8\u00f4\u00e8\u00ea\u00e0\u00f2\u00ee\u00f0\u00ee\u00e2
     *
     * @param request
     * @return returns ru.rsdn.janus.UserResponse
     */
    @WebMethod(operationName = "GetUserByIds", action = "http://rsdn.ru/Janus/GetUserByIds")
    @WebResult(name = "GetUserByIdsResult", targetNamespace = "http://rsdn.ru/Janus/")
    @RequestWrapper(localName = "GetUserByIds", targetNamespace = "http://rsdn.ru/Janus/", className = "ru.rsdn.janus.GetUserByIds")
    @ResponseWrapper(localName = "GetUserByIdsResponse", targetNamespace = "http://rsdn.ru/Janus/", className = "ru.rsdn.janus.GetUserByIdsResponse")
    public UserResponse getUserByIds(
            @WebParam(name = "request", targetNamespace = "http://rsdn.ru/Janus/")
                    UserByIdsRequest request
    );

    /**
     * \u00c4\u00ee\u00e1\u00e0\u00e2\u00eb\u00e5\u00ed\u00e8\u00e5 \u00e8\u00e7\u00ec\u00e5\u00ed\u00e5\u00ed\u00e8\u00e9 \u00e2 \u00f4\u00ee\u00f0\u00f3\u00ec\u00fb
     *
     * @param postRequest
     */
    @WebMethod(operationName = "PostChange", action = "http://rsdn.ru/Janus/PostChange")
    @RequestWrapper(localName = "PostChange", targetNamespace = "http://rsdn.ru/Janus/", className = "ru.rsdn.janus.PostChange")
    @ResponseWrapper(localName = "PostChangeResponse", targetNamespace = "http://rsdn.ru/Janus/", className = "ru.rsdn.janus.PostChangeResponse")
    public void postChange(
            @WebParam(name = "postRequest", targetNamespace = "http://rsdn.ru/Janus/")
                    PostRequest postRequest
    );

    /**
     * \u00cf\u00ee\u00e4\u00f2\u00e2\u00e5\u00f0\u00e6\u00e4\u00e5\u00ed\u00e8\u00e5 \u00e4\u00ee\u00e1\u00e0\u00e2\u00eb\u00e5\u00ed\u00e8\u00ff \u00e8\u00e7\u00ec\u00e5\u00ed\u00e5\u00ed\u00e8\u00e9 \u00e2 \u00f4\u00ee\u00f0\u00f3\u00ec\u00fb
     *
     * @return returns ru.rsdn.janus.PostResponse
     */
    @WebMethod(operationName = "PostChangeCommit", action = "http://rsdn.ru/Janus/PostChangeCommit")
    @WebResult(name = "PostChangeCommitResult", targetNamespace = "http://rsdn.ru/Janus/")
    @RequestWrapper(localName = "PostChangeCommit", targetNamespace = "http://rsdn.ru/Janus/", className = "ru.rsdn.janus.PostChangeCommit")
    @ResponseWrapper(localName = "PostChangeCommitResponse", targetNamespace = "http://rsdn.ru/Janus/", className = "ru.rsdn.janus.PostChangeCommitResponse")
    public PostResponse postChangeCommit();

    /**
     * \u00cf\u00f0\u00ee\u00e2\u00e5\u00f0\u00ea\u00e0 \u00e0\u00ea\u00f2\u00e8\u00e2\u00ed\u00ee\u00f1\u00f2\u00e8
     */
    @WebMethod(operationName = "Check", action = "http://rsdn.ru/Janus/Check")
    @RequestWrapper(localName = "Check", targetNamespace = "http://rsdn.ru/Janus/", className = "ru.rsdn.janus.Check")
    @ResponseWrapper(localName = "CheckResponse", targetNamespace = "http://rsdn.ru/Janus/", className = "ru.rsdn.janus.CheckResponse")
    public void check();

    /**
     * ���������� ����� ��������� � ����������
     *
     * @param request
     * @return returns ru.rsdn.janus.ViolationResponse
     */
    @WebMethod(operationName = "GetNewViolations", action = "http://rsdn.ru/Janus/GetNewViolations")
    @WebResult(name = "GetNewViolationsResult", targetNamespace = "http://rsdn.ru/Janus/")
    @RequestWrapper(localName = "GetNewViolations", targetNamespace = "http://rsdn.ru/Janus/", className = "ru.rsdn.janus.GetNewViolations")
    @ResponseWrapper(localName = "GetNewViolationsResponse", targetNamespace = "http://rsdn.ru/Janus/", className = "ru.rsdn.janus.GetNewViolationsResponse")
    public ViolationResponse getNewViolations(
            @WebParam(name = "request", targetNamespace = "http://rsdn.ru/Janus/")
                    ViolationRequest request
    );

}
